name: 'Jira Report Uploader'
description: 'Upload test reports to JIRA'
inputs:
  jira-instance:  # id of input
    description: 'jira instance address'
    required: true
    default: ''
    
  jira-user:  # id of input
    description: 'jira user that will create the issues'
    required: true
    default: ''

  jira-token:  # id of input
    description: 'jira authentication token'
    required: true
    default: ''

  xray-client:  # id of input
    description: 'XRay Client'
    required: true
    default: ''

  xray-token:  # id of input
    description: 'XRay authentication token'
    required: true
    default: ''

  issue-summary:  # id of input
    description: 'Jira issue summary for the test execution'
    required: true
    default: ''

  project:  # id of input
    description: 'Project where the issue will be created'
    required: true
    default: ''

  report-folder:  # id of input
    description: 'Folder where reports are available'
    required: false
    default: 'report'

  jira-in-progress-transition:  # id of input
    description: 'Jira transition to In-progress'
    required: false
    default: '21'

  jira-done-transition:  # id of input
    description: 'Jira transition to done'
    required: false
    default: '41'

  fix-version:  # id of input
    description: 'Jira fixVersion'
    required: true
    default: ''

outputs:
  random-number: 
    description: "Test execution created"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/jira_uploader.sh ${{ inputs.jira-instance }} ${{ inputs.jira-user }} ${{ inputs.jira-token }} ${{ inputs.xray-client }} ${{ inputs.xray-token }} ${{ inputs.project }} ${{ inputs.issue-summary }} ${{ inputs.report-folder }} ${{ inputs.fix-version }} ${{ inputs.jira-in-progress-transition }} ${{ inputs.jira-done-transition }}
      shell: bash

