on: [push]

jobs:
  jira-report-uploader:
    runs-on: ubuntu-latest
    name: Upload test reports to JIRA
    steps:
    - uses: actions/checkout@v2
    - id: jira
      uses: felipecpc/github-action-jira-report-uploader@v2.0.0
      with:
        jira-instance: 'jira_instance'
        jira-user: 'jira@email.com'
        jira-token: 'jira_token'
        jira-in-progress-transition: '21'
        jira-done-transition: '41'
        xray-client: 'xray_client'
        xray-token: 'xray_token'
        project: 'PJ'
        issue-summary: '"[Automated Tests] This is the issue summary"'
        report-folder: 'reports'
        fix-version: 'v1.0.0'
